### ISSUE TITLE
Vestiging download mislukt: Uw account heeft niet genoeg rechten.

### ISSUE THREAD

**Issue by bshogeman** [DwayneSelsig/Somtoday2MicrosoftSchoolDataSync#1]
Het service account schijnt volgens somtoday zelf de juiste machtigingen te hebben.
Toch krijg ik de melding: Vestiging download mislukt: Uw account heeft niet genoeg rechten.
BooleanFilterBylocation op False maakt geen verschil.
Wat kan dit zijn?

**Comment by DwayneSelsig** [comment]
De melding "Uw account heeft niet genoeg rechten." is afkomstig vanuit de Umservice van Somtoday. Het account hoeft alleen toegang tot de Umservice te hebben. Kijk in Somtoday bij:

Beheer -> rollen en rechten
Maak een rol aan.
Ga naar het tabblad "Webservices"
Klik "User Management Service" open
Vink minimaal aan:
- inrichting
- leerlingen
- medewerkers
